project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "US Education Score Trends"
  author:
    - Omri Habot (oh2263)
    - Vishwa Bhatt (vmb2146)
    - Anna Micros (am6529)
  repo-url: https://github.com/ohabot-cu/US-Education-Trends
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


