# Introduction

Since the COVID-19 pandemic, average reading and math scores have been on a steady decline in the United States. Across almost all demographics nationwide, data from the National Assessment of Educational Progress reveals a steady downward trend in student performance on standardized reading and mathematics assessments. Average test scores among 13-year-olds in 2023 were the lowest in decades, 4 points lower in reading and 9 points lower in math than in 2019, respectively. Though this academic decline does not come as a complete surprise in the wake of school closures and online learning at the height of the pandemic, lower literacy and math skills have continued to drop across almost all demographic groups, including variations in age, gender, race, and region. We have chosen this topic for our final project to draw attention to this salient issue, highlight potential areas of achievement where students are struggling most, and contribute to the conversation of how to move forward in a post-pandemic world. For this project in particular, we are interested in exploring where academic achievement falls shortest across these demographics, with the ultimate goal to explore which groups of students continue to be most disserviced by the U.S. education system. We will examine how the downward trend of reading and math scores differs across the mentioned variables to understand which students were hit hardest by the transitions from in-classroom to online learning and back again. We are interested in studying the following questions: how does academic performance across the United States compare to pre-pandemic and even earlier performances? Which groups of students face the most difficulty in achieving pre-pandemic rates of academic achievement? Which groups of students are most at risk of education disparity if the current trends continue? 
